package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "archive_example",
    srcs = ["archive_example.cc"],
    deps = [
        "@boost//:archive",
        "@boost//:serialization",
    ],
)
